### ISSUE TITLE
Supported GCP regions

### ISSUE THREAD

**Issue by aTeoke** [api3dao/old-api3-docs#978] opened 2022-08-17 14:35 UTC
Document supported GCP regions as well as highlight unsupported GCP regions based on Martin's K. testing

**Comment by dcroote** [comment] 2022-08-21 16:58
Tagging @kolenic-martin

**Comment by dcroote** [comment] 2022-09-12 02:10
Duplicate of #1001, closed by #1012

**Closed as completed by dcroote** 2022-09-12 02:10 UTC
