### ISSUE TITLE
[OIS Specification] fixedOperationParameters not really optional

### ISSUE THREAD

**Issue by An-dz** [api3dao/old-api3-docs#71] opened 2021-05-04 19:26 UTC
The OIS specification claims that `fixedOperationParameters` is optional, but in reality it's not. What is optional is whether it contains any elements in its array.

Either the specification should clarify it by claiming it's required but don't need any child elements, or the airnode code should first check its existence before doing a reduce.

**Comment by wkande** [comment] 2021-05-05 22:42
Thanks, I'm going to pass this by a **dev** to look at first and then set the docs accordingly.

**Comment by bbenligiray** [comment] 2021-05-06 08:11
The intended behavior is for `fixedOperationParameters` to be required even if it's empty. So we should update the docs to clarify that.

**Comment by wkande** [comment] 2021-05-06 16:55
This correction will be part of tonight's build of the docs.

**Closed as completed by wkande** 2021-05-06 16:55 UTC
Labels: Documentation
